version: "3.5"
services:
  local:
    build:
      context: .
    image: node:10-alpine
    volumes:
      - ./src:/app/src
    container_name: api-local
    environment:
      NODE_ENV: local
      AWS_ACCESS_KEY_ID: anykey
      AWS_SECRET_ACCESS_KEY: anysecret
      AWS_REGION: us-east-2
    ports:
      - "3000:3000"
      - "9229:9229"
    tty: true
    entrypoint: ["npm", "run", "dev"]
  localstack:
    image: localstack/localstack
    container_name: api-dynamodb_localstack
    environment:
      SERVICES: dynamodb
    ports:
      - "4566:4566"
  setup:
    image: mesosphere/aws-cli
    container_name: api-dynamodb_setup
    volumes:
      - ./setup:/setup
    environment:
      AWS_ACCESS_KEY_ID: anykey
      AWS_SECRET_ACCESS_KEY: anysecret
      AWS_DEFAULT_REGION: us-east-2
    entrypoint: [""]
    depends_on:
      - localstack
    command: ["/setup/setup.sh"]
  dev:
      build:
      context: .
    image: node:10-alpine
    volumes:
      - ./src:/app/src
    container_name: api-dev
    environment:
      NODE_ENV: local
      PORT: 80
    ports:
      - "80:3000"
      - "9229:9229"
    tty: true
    entrypoint: ["npm", "run", "dev"]
networks:
  default:
    name: api-dynamodb
